language: python
python: 
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"
  - "pypy"

# command to install dependencies
install:
  - "pip install nose coverage"
  - "pip install -r requirements.txt"
# command to run tests
script:
  #- tox
  - nosetests
after_success:
  coveralls
